### ISSUE TITLE
Changing the header files does not trigger a rebuild of the unittests

### ISSUE THREAD

**Issue by Dobiasd** [Dobiasd/FunctionalPlus#113]
Since #112 I encounter a new effect when changing the library and running the unittests.

My usual workflow looks like this:

initially:
```
rm -r build
mkdir build
cd build
cmake -DUNITTEST=ON ..
make unittest
```

later:
```
# change something in one of the header files
make unittest
```

With the old versions of `CMakeLists.txt` and `test/CMakeLists.txt` it still works, but with the new ones the second `make unittest` does not rebuild the tests. It just ignores the changes in the header files. I have to run `sudo make install` to rebuild the tests.

@offa and @theodelrieu Is this intended and my workflow is just strange? Or do you think it would be possible and helpful to change the cmake configuration to support this again?

**Comment by theodelrieu** [comment]
I usually launch `ninja && ninja test`, but `ninja unittest` works for me.

Could you try with `cmake -G Ninja`?

**Comment by Dobiasd** [comment]
Sorry, I'm new to `ninja`. Could you give me a hand on getting it up and running?

I just did
```
rm -r build
mkdir build
cd build
cmake -DUNITTEST=ON ..
sudo apt install ninja
sudo ninja && ninja test
```
and it starts running, but does not do anything.

`$ cmake -G Ninja` results in the following
```
CMake Error: The source directory "/home/tobias/data/Tobias/Projekte/Fun/FunctionalPlus/FunctionalPlus/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

**Comment by Dobiasd** [comment]
Running `cmake -G Ninja` outside of the build directory results in the following:

```
cmake -G Ninja
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler using: Ninja
CMake Error:
  The detected version of Ninja (log: ninja version 0.1.3 initializing) is
  less than the version of Ninja required by CMake (1.3).


CMake Error: Internal CMake error, TryCompile generation of cmake failed
-- Check for working C compiler using: Ninja -- broken
CMake Error at /usr/share/cmake-3.5/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "/usr/bin/cc" is not able to compile a simple test program.

  It fails with the following output:

   

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)


-- Configuring incomplete, errors occurred!
```

**Comment by theodelrieu** [comment]
I have Ninja 1.8.2, could you try to update it?

Also I meant `cmake -G Ninja ..`, launched from the build directory, sorry.

**Comment by Dobiasd** [comment]
Ok, I now have the latest release, but still can not get it running.

```
FunctionalPlus/build$ cmake -G Ninja ..
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

```
FunctionalPlus/build$ cmake -G ninja ..
CMake Error: Could not create named generator ninja

Generators
  Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  Watcom WMake                 = Generates Watcom WMake makefiles.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
  KDevelop3                    = Generates KDevelop 3 project files.
  KDevelop3 - Unix Makefiles   = Generates KDevelop 3 project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.
```

**Comment by theodelrieu** [comment]
This is really weird, can you simply run `ninja`?

If you're on Linux you have to `apt install ninja-build`, not `ninja`.

**Comment by Dobiasd** [comment]
Ah, thanks a lot. Now it looks much better:
```
FunctionalPlus$ rm -r build/
FunctionalPlus$ mkdir build
FunctionalPlus$ cd build/
FunctionalPlus/build$ cmake -DUNITTEST=ON -G Ninja ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler using: Ninja
-- Check for working C compiler using: Ninja -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler using: Ninja
-- Check for working CXX compiler using: Ninja -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ===( FunctionalPlus 0.2 )===
-- Building Unit Tests ON
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found doctest: /usr/local/include  
-- Configuring done
-- Generating done
-- Build files have been written to: FunctionalPlus/build

/FunctionalPlus/build$ ninja && ninja test
[72/72] Linking CXX executable test/maybe_test
[1/1] Running tests...
Test project /home/tobias/data/Tobias/Projekte/Fun/FunctionalPlus/FunctionalPlus/build
      Start  1: show_versions
 1/36 Test  #1: show_versions ....................   Passed    0.01 sec
      Start  2: compare_test
 2/36 Test  #2: compare_test .....................   Passed    0.01 sec
      Start  3: composition_test
 3/36 Test  #3: composition_test .................   Passed    0.02 sec
      Start  4: container_common_test
 4/36 Test  #4: container_common_test ............   Passed    0.02 sec
      Start  5: container_properties_test
 5/36 Test  #5: container_properties_test ........   Passed    0.01 sec
      Start  6: container_traits_test
 6/36 Test  #6: container_traits_test ............   Passed    0.01 sec
      Start  7: curry_test
 7/36 Test  #7: curry_test .......................   Passed    0.00 sec
      Start  8: extrapolate_test
 8/36 Test  #8: extrapolate_test .................   Passed    0.00 sec
      Start  9: filter_test
 9/36 Test  #9: filter_test ......................   Passed    0.01 sec
      Start 10: function_traits_test
10/36 Test #10: function_traits_test .............   Passed    0.00 sec
      Start 11: fwd_test
11/36 Test #11: fwd_test .........................   Passed    0.01 sec
      Start 12: generate_test
12/36 Test #12: generate_test ....................   Passed    0.01 sec
      Start 13: interpolate_test
13/36 Test #13: interpolate_test .................   Passed    0.02 sec
      Start 14: invoke_test
14/36 Test #14: invoke_test ......................   Passed    0.00 sec
      Start 15: maps_test
15/36 Test #15: maps_test ........................   Passed    0.02 sec
      Start 16: maybe_test
16/36 Test #16: maybe_test .......................   Passed    0.03 sec
      Start 17: numeric_test
17/36 Test #17: numeric_test .....................   Passed    0.02 sec
      Start 18: optimize_test
18/36 Test #18: optimize_test ....................   Passed    0.01 sec
      Start 19: pairs_test
19/36 Test #19: pairs_test .......................   Passed    0.01 sec
      Start 20: queue_test
20/36 Test #20: queue_test .......................   Passed    0.00 sec
      Start 21: raii_test
21/36 Test #21: raii_test ........................   Passed    0.02 sec
      Start 22: read_test
22/36 Test #22: read_test ........................   Passed    0.01 sec
      Start 23: readme_examples_test
23/36 Test #23: readme_examples_test .............   Passed    0.01 sec
      Start 24: result_test
24/36 Test #24: result_test ......................   Passed    0.02 sec
      Start 25: replace_test
25/36 Test #25: replace_test .....................   Passed    0.01 sec
      Start 26: search_test
26/36 Test #26: search_test ......................   Passed    0.01 sec
      Start 27: sets_test
27/36 Test #27: sets_test ........................   Passed    0.00 sec
      Start 28: shared_ref_test
28/36 Test #28: shared_ref_test ..................   Passed    0.02 sec
      Start 29: show_test
29/36 Test #29: show_test ........................   Passed    0.02 sec
      Start 30: side_effects_test
30/36 Test #30: side_effects_test ................   Passed    0.01 sec
      Start 31: split_test
31/36 Test #31: split_test .......................   Passed    0.01 sec
      Start 32: stringtools_test
32/36 Test #32: stringtools_test .................   Passed    0.01 sec
      Start 33: transform_test
33/36 Test #33: transform_test ...................   Passed    0.01 sec
      Start 34: tree_test
34/36 Test #34: tree_test ........................   Passed    0.01 sec
      Start 35: udemy_course_test
35/36 Test #35: udemy_course_test ................   Passed    0.02 sec
      Start 36: variant_test
36/36 Test #36: variant_test .....................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 36

Total Test time (real) =   0.70 sec
```

And changing something in a header file before running `ninja && ninja test` again let's it recompile everything as needed.

For me it is OK to use ninja from now on. However, out of interest, would it be possible to archieve this (rebuild on changes with `make unittest`) also with the modernized cmake files?

**Comment by offa** [comment]
This is a strange behaviour. In general, the `unittest` target is intended to *run* the tests only. But as the tests depend on the library they are build before. Changes of the libraries / header files should therefore implicitly trigger a rebuild of the related tests. 

@Dobiasd What happens if you build the `all` target before running the tests (`make all`).

What's curious: I can't reproduce the problem on my system. The steps i tried (using a fresh build dir and _Make_):

1. Run CMake with Tests enabled
1. Build and run the tests
1. Add a blank line to `fwd.hpp` (just to change something)
1. `make unittest` – build is triggered
1. Remove a line of `raii.hpp`
1. `make unittest` – build is triggered
1. Reset of the previous changes (using git) 
1. `make unittest` – build is triggered

(Linux using CMake 3.10, Make 4.2.1, GCC 7.2.0)

**Comment by Dobiasd** [comment]
Interesting. I just tried again with a fresh checkout:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

$ cmake --version
cmake version 3.5.1
CMake suite maintained and supported by Kitware (kitware.com/cmake).

$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
Licence GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

git clone https://github.com/Dobiasd/FunctionalPlus
cd FunctionalPlus
mkdir build
cd build
cmake -DUNITTEST=ON ..
make unittest # builds everything
echo "nonsense" > ../include/fplus/fwd.hpp
make unittest # does not rebuild
```

I will try to reproduce the problem on another machine this evening.

**Comment by offa** [comment]
What happens if you `touch` the modified file?

**Comment by Dobiasd** [comment]
```
FunctionalPlus/build$ make unittest # builds
FunctionalPlus/build$ echo "nonsense" > ../include/fplus/fwd.hpp 
FunctionalPlus/build$ touch ../include/fplus/fwd.hpp 
FunctionalPlus/build$ make unittest # does not build
```

Oh, and I forgot to answer this in my previous reply: using `make all` also does not change the behavior.

**Comment by offa** [comment]
I have literally copy & pasted those commands, but the last one still builds for me¹. I'm going to test this on another system. 

Curiously, it works on Ninja builds, but fails under some circumstances on Make.

-------------
¹ Of course it doesn't compile, as 'nonsense is not a type'.

**Comment by Dobiasd** [comment]
Perhaps it has to do with the fact that currently I'm in a VirtualBox. The other machine is using linux natively but with the same software versions. I will report the results.

**Comment by offa** [comment]
If you have a minute, can you test with this patch applied?

```
diff --git a/test/CMakeLists.txt b/test/CMakeLists.txt
index ce4423e..59126c5 100644
--- a/test/CMakeLists.txt
+++ b/test/CMakeLists.txt
@@ -87,5 +87,7 @@ add_custom_target(unittest show_versions
                         COMMAND variant_test
                         COMMENT "Running unittests\n\n"
                         VERBATIM
+
+                        DEPENDS fplus
                         )
```

As noted above, there's an implicit dependency between `unittest` and `fplus` targets.  Therefore adding this dependency information shouldn't be necessary, but better lets find out.

**Comment by Dobiasd** [comment]
I applied the patch. `test/CMakeLists.txt` now looks as follows:
```
FunctionalPlus/build$ cat ../test/CMakeLists.txt

find_package(doctest REQUIRED)


function(add_test_suite name)
    add_executable(${name} ${name}.cpp)
    add_test(NAME ${name} COMMAND ${name})

    target_compile_options(${name} PRIVATE ${COMPILE_OPTIONS})
    target_include_directories(${name} SYSTEM PRIVATE ${doctest_INCLUDE_DIR})
    target_link_libraries(${name} PRIVATE fplus ${CMAKE_THREAD_LIBS_INIT})
endfunction()

add_test_suite(show_versions)
add_test_suite(compare_test)
add_test_suite(composition_test)
add_test_suite(container_common_test)
add_test_suite(container_properties_test)
add_test_suite(container_traits_test)
add_test_suite(curry_test)
add_test_suite(extrapolate_test)
add_test_suite(filter_test)
add_test_suite(function_traits_test)
add_test_suite(fwd_test)
add_test_suite(generate_test)
add_test_suite(interpolate_test)
add_test_suite(invoke_test)
add_test_suite(maps_test)
add_test_suite(maybe_test)
add_test_suite(numeric_test)
add_test_suite(optimize_test)
add_test_suite(pairs_test)
add_test_suite(queue_test)
add_test_suite(raii_test)
add_test_suite(read_test)
add_test_suite(readme_examples_test)
add_test_suite(result_test)
add_test_suite(replace_test)
add_test_suite(search_test)
add_test_suite(sets_test)
add_test_suite(shared_ref_test)
add_test_suite(show_test)
add_test_suite(side_effects_test)
add_test_suite(split_test)
add_test_suite(stringtools_test)
add_test_suite(transform_test)
add_test_suite(tree_test)
add_test_suite(udemy_course_test)
add_test_suite(variant_test)


add_custom_target(unittest show_versions
                        COMMAND compare_test
                        COMMAND composition_test
                        COMMAND container_common_test
                        COMMAND container_properties_test
                        COMMAND container_traits_test
                        COMMAND curry_test
                        COMMAND extrapolate_test
                        COMMAND filter_test
                        COMMAND function_traits_test
                        COMMAND fwd_test
                        COMMAND generate_test
                        COMMAND interpolate_test
                        COMMAND invoke_test
                        COMMAND maps_test
                        COMMAND maybe_test
                        COMMAND numeric_test
                        COMMAND optimize_test
                        COMMAND pairs_test
                        COMMAND queue_test
                        COMMAND raii_test
                        COMMAND read_test
                        COMMAND readme_examples_test
                        COMMAND result_test
                        COMMAND replace_test
                        COMMAND search_test
                        COMMAND sets_test
                        COMMAND shared_ref_test
                        COMMAND show_test
                        COMMAND side_effects_test
                        COMMAND split_test
                        COMMAND stringtools_test
                        COMMAND transform_test
                        COMMAND tree_test
                        COMMAND udemy_course_test
                        COMMAND variant_test
                        COMMENT "Running unittests\n\n"
                        VERBATIM

                        DEPENDS fplus
                        )
```
But the behavior is still the same:
```
FunctionalPlus/build$ make unittest # builds
FunctionalPlus/build$ echo nonsense > ../include/fplus/fwd.hpp
FunctionalPlus/build$ touch ../include/fplus/fwd.hpp
FunctionalPlus/build$ make unittest # does not build
```

**Comment by offa** [comment]
Tested *master* using a docker ubuntu image.
- Ubuntu 16.04
- CMake 3.9.5
- Make 4.1
- GCC 7.2

 It's working there too. What I've noted: In both cases I'm running a more recent version of Cmake (3.10 / 3.9). Could this cause the issue?

**Comment by Dobiasd** [comment]
```
FunctionalPlus/build$ sudo apt purge cmake
FunctionalPlus/build$ ~/Downloads/cmake-3.10.0-Linux-x86_64/bin/cmake --version
cmake version 3.10.0
CMake suite maintained and supported by Kitware (kitware.com/cmake).

FunctionalPlus/build$ ~/Downloads/cmake-3.10.0-Linux-x86_64/bin/cmake -DUNITTEST=ON ..
FunctionalPlus/build$ make unittest # builds
FunctionalPlus/build$ echo nonsense > ../include/fplus/fwd.hpp
FunctionalPlus/build$ make unittest # does not build
```

**Comment by offa** [comment]
A simple `make` doesn't build either at this point?

**Comment by Dobiasd** [comment]
nope

**Comment by offa** [comment]
Are the demo apps working (eg. `make 99_problems`)?

**Comment by Dobiasd** [comment]
Yes, with `99_problems` rebuilds as intended:

```
FunctionalPlus/build $ make 99_problems
Scanning dependencies of target 99_problems
[ 50%] Building CXX object CMakeFiles/99_problems.dir/examples/99_problems.cpp.o
[100%] Linking CXX executable 99_problems
[100%] Built target 99_problems
FunctionalPlus/build $ echo nonsense > ../include/fplus/fwd.hpp 
FunctionalPlus/build $ make 99_problems
# builds and produced the wanted big wall of errors
```

By the way, I am now at my home PC with Linux running natively, and issue with `make unittest` also occurs here.
```
make unittest -j # builds
echo nonsense > ../include/fplus/fwd.hpp
make unittest -j # runs without rebuilding
```

**Comment by offa** [comment]
I've pushed a [branch](https://github.com/offa/FunctionalPlus/tree/experimental/issue113/make-issue) to investigate this problem. 

I have modified the [Travis settings](https://github.com/offa/FunctionalPlus/blob/experimental/issue113/make-issue/.travis.yml) to execute the steps we used so far. The [build is triggered](https://travis-ci.org/offa/FunctionalPlus/builds/316046991#L1431) (of course it wont compile).

**Comment by Dobiasd** [comment]
Good idea to test it on travis. :+1: I see there it works as inteded.

Just to make sure I'm not crazy, I just scripted the whole process, ran it in another vbox and captured the screencast.

Here it is: https://youtu.be/_LEtBfPWY9g The interesting part happens at 2:05.

Am I doing something embarrassing wrong?

**Comment by offa** [comment]
> Am I doing something embarrassing wrong?

No, there's everything. Interestingly this is (or should be) the same as on Travis. 

----------------------------------

What i don't understand at this point: The demo links the fplus target the same way as each test does. Using the target within `add_custom_target()` indirectly establishes a dependency to fplus. But even making that explicit doesn't make a difference.

**Comment by offa** [comment]
I don't expect this as reason, but how's the situation after reverting `add_test_suite()` to a macro instead of function?

```patch
diff --git a/test/CMakeLists.txt b/test/CMakeLists.txt
index ce4423e..ee037e7 100644
--- a/test/CMakeLists.txt
+++ b/test/CMakeLists.txt
@@ -2,14 +2,14 @@
 find_package(doctest REQUIRED)
 
 
-function(add_test_suite name)
+macro(add_test_suite name)
     add_executable(${name} ${name}.cpp)
     add_test(NAME ${name} COMMAND ${name})
 
     target_compile_options(${name} PRIVATE ${COMPILE_OPTIONS})
     target_include_directories(${name} SYSTEM PRIVATE ${doctest_INCLUDE_DIR})
     target_link_libraries(${name} PRIVATE fplus ${CMAKE_THREAD_LIBS_INIT})
-endfunction()
+endmacro()
 
 add_test_suite(show_versions)
 add_test_suite(compare_test)
            
```

**Comment by Dobiasd** [comment]
`test/CMakeLists.txt` now looks like this

```
find_package(doctest REQUIRED)


macro(add_test_suite name)
    add_executable(${name} ${name}.cpp)
    add_test(NAME ${name} COMMAND ${name})

    target_compile_options(${name} PRIVATE ${COMPILE_OPTIONS})
    target_include_directories(${name} SYSTEM PRIVATE ${doctest_INCLUDE_DIR})
    target_link_libraries(${name} PRIVATE fplus ${CMAKE_THREAD_LIBS_INIT})
endmacro()

add_test_suite(show_versions)
add_test_suite(compare_test)
add_test_suite(composition_test)
add_test_suite(container_common_test)
add_test_suite(container_properties_test)
add_test_suite(container_traits_test)
add_test_suite(curry_test)
add_test_suite(extrapolate_test)
add_test_suite(filter_test)
add_test_suite(function_traits_test)
add_test_suite(fwd_test)
add_test_suite(generate_test)
add_test_suite(interpolate_test)
add_test_suite(invoke_test)
add_test_suite(maps_test)
add_test_suite(maybe_test)
add_test_suite(numeric_test)
add_test_suite(optimize_test)
add_test_suite(pairs_test)
add_test_suite(queue_test)
add_test_suite(raii_test)
add_test_suite(read_test)
add_test_suite(readme_examples_test)
add_test_suite(result_test)
add_test_suite(replace_test)
add_test_suite(search_test)
add_test_suite(sets_test)
add_test_suite(shared_ref_test)
add_test_suite(show_test)
add_test_suite(side_effects_test)
add_test_suite(split_test)
add_test_suite(stringtools_test)
add_test_suite(transform_test)
add_test_suite(tree_test)
add_test_suite(udemy_course_test)
add_test_suite(variant_test)


add_custom_target(unittest show_versions
                        COMMAND compare_test
                        COMMAND composition_test
                        COMMAND container_common_test
                        COMMAND container_properties_test
                        COMMAND container_traits_test
                        COMMAND curry_test
                        COMMAND extrapolate_test
                        COMMAND filter_test
                        COMMAND function_traits_test
                        COMMAND fwd_test
                        COMMAND generate_test
                        COMMAND interpolate_test
                        COMMAND invoke_test
                        COMMAND maps_test
                        COMMAND maybe_test
                        COMMAND numeric_test
                        COMMAND optimize_test
                        COMMAND pairs_test
                        COMMAND queue_test
                        COMMAND raii_test
                        COMMAND read_test
                        COMMAND readme_examples_test
                        COMMAND result_test
                        COMMAND replace_test
                        COMMAND search_test
                        COMMAND sets_test
                        COMMAND shared_ref_test
                        COMMAND show_test
                        COMMAND side_effects_test
                        COMMAND split_test
                        COMMAND stringtools_test
                        COMMAND transform_test
                        COMMAND tree_test
                        COMMAND udemy_course_test
                        COMMAND variant_test
                        COMMENT "Running unittests\n\n"
                        VERBATIM
                        )
```
I freshly created the `build` directory, but the issue still persists.

**However** I just removed my installed version of `fplus` with `sudo rm -r /usr/local/include/fplus/` and then a rebuild is triggered after `echo nonsense > ../include/fplus/fwd.hpp`. So the installed version seems to be preferred if it exists.

Could you please add a `sudo make install` after the first `make unittest` in the travis script of your branch as a test?

**Comment by Dobiasd** [comment]
I think I got it. :)
`FunctionalPlus/CMakeLists.txt` currently looks like that
```
...
target_include_directories(fplus INTERFACE
                       $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
                       $<INSTALL_INTERFACE:include>
                        )
...
```

If I change it like so, the issue is resolved:

```
...
target_include_directories(fplus INTERFACE
                       $<INSTALL_INTERFACE:include>
                       $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
                        )
...
```

**Comment by offa** [comment]
Seriously? I don't see any change than swapping the two `$<…>` lines!?

**Comment by Dobiasd** [comment]
Exactly. :D

**Comment by offa** [comment]
Then i should definitely go and fix this in one of my projects too! 😄

**Comment by Dobiasd** [comment]
Could you verify it on your travis test branch by adding `sudo make install` after the first `make unittest`, just to make sure it is not a peculiarity of my machines?

**Comment by offa** [comment]
Yes, makes sense.

**Comment by offa** [comment]
[Installation Ok](https://travis-ci.org/offa/FunctionalPlus/builds/316087924#L1325) on travis.

**Comment by offa** [comment]
I just noticed: Didn't change the two lines prior the commit.

I'll fix that an report back.

**Comment by Dobiasd** [comment]
After deleting (`sudo rm -r /usr/local/include/fplus/`) everything works as expected, even after using `sudo make install` again.
It is OK on both my native linux pc and in the screencast vbox:

```
git clone https://github.com/Dobiasd/FunctionalPlus
cd FunctionalPlus
mkdir build
cd build
sudo rm -r /usr/local/include/fplus/ # delete installed version
cmake -DUNITTEST=ON ..
make unittest # build
sudo make install # install
echo nonsense > ../include/fplus/fwd.hpp
make unittest # rebuilds everything with errors as expected
```

video: https://youtu.be/oV8SP5Z4pDo

So I guess there is no need to swap the two `target_include_directories` lines. Since I now can not reproduce the problem any more, I think we're done.

I'm sorry for the work I caused simply due to something that seems to have been a peculiarity of my systems.

**Comment by Dobiasd** [comment]
To make this issue complete, I just also tested on my third system (Lubuntu-vbox). After doing `sudo rm -r /usr/local/include/fplus/` once the problem is gone here too.

Sorry again and thanks for all the help. :)
